### ISSUE TITLE
Passing props to elements

### ISSUE THREAD

**Issue by milewskibogumil** [theisel/astro-portabletext#156]
Hello!

I would like to know how to pass a scoped element props to the elements.

```
/* page.astro */
---
const value = [ ];
---
<div class="paragraph">
  <MyPortableText value={value} />
</div>

<!-- The styles have to be here, as it is unique to this page -->
<style lang="scss">
  .paragraph {
    color: green;
    ul {
      color: red;
    }
  }
</style>
```

```
/* MyPortableText.astro */
---
import { PortableText } from 'astro-portabletext';
import { mergeComponents } from 'astro-portabletext/utils';
import Block from './Block.astro';
import List from './List.astro';
import ListItem from './ListItem.astro';
import Mark from './Mark.astro';

type PortableTextProps = Parameters<typeof PortableText>[0];

export type Props = Pick<PortableTextProps, 'value' | 'components'>;

const { value, components: overrideComponents = {} } = Astro.props;

const components = mergeComponents(
  {
    block: Block,
    list: List,
    listItem: ListItem,
    mark: Mark,
  },
  overrideComponents,
);
---
<PortableText value={value} components={components} />
```

Everything in that text is green – that's correct, but the `ul` inside isn't red as I specified.

I tried almost every strategy, but nothing works. Is there any way to pass all props to all the elements? The astro scoped styles add something like `data-astro-cid-someid` and I need to pass that for every element with `{...props}`.

**Comment by theisel** [comment]
Hi @milewskibogumil the best way is to use `:global()` selector. See Astro docs [mix global & scoped CSS rules](https://docs.astro.build/en/guides/styling/#global-styles)

```diff
<style lang="scss">
  .paragraph {
    color: green;
-   ul {
+  :global(ul) {
      color: red;
    }
  }
</style>
```

**Comment by milewskibogumil** [comment]
Yes, it is certainly an option, but I need to have this SCSS scoped. There is no way to pass props from astro to Portable Text elements?

**Comment by milewskibogumil** [comment]
That's it, thank you @theisel!
