### ISSUE TITLE
PortableText duplicated list items

### ISSUE THREAD

**Issue by aFrontendDev** [theisel/astro-portabletext#175]
List items are duplicated when they also contain a style and there is more than 1 child element, such as when a word is bold/italic/etc

Example here: https://stackblitz.com/edit/github-4darib-nrxitl4i?file=src%2Fcomponents%2Fportabletext%2FPortableText.astro,src%2Fpages%2Findex.astro

The use-case here is that our content editors want to use text styles inside a list, e.g. a bullet list where the list items have a custom text style that makes the text larger than usual. They also want to be able to make certain words bold or italic, this results in a list item with a style (in our case the style could be "standfirst") and also results in the block having multiple elements in the children array. The output of this is that the content of the list item gets duplicated

![Screenshot 2024-12-12 at 10 51 58](https://github.com/user-attachments/assets/f3c353b0-a982-40f8-b6d9-3e63347d0c48)

example of the JSON that gets fed into the PortableText:
```
{
  "_key": "a8f6c37f1f5d",
  "_type": "block",
  "children": [
    {
      "_key": "f69fa0972de1",
      "_type": "span",
      "marks": [],
      "text": "list standfirst "
    },
    {
      "_key": "12e6dbf8f10a",
      "_type": "span",
      "marks": [
        "strong"
      ],
      "text": "bold"
    },
  ],
  "level": 1,
  "listItem": "bullet",
  "markDefs": [],
  "style": "standfirst"
}
```

**Comment by theisel** [comment]
Hi @aFrontendDev thanks for posting this issue and providing a clear example on Stackblitz. I'll need to do some digging, as there may be a bug with `nestLists` from the `@portabletext/toolkit` dependency, or there might be an underlying bug in this library itself. 

I'll keep you updated on my progress.

**Comment by theisel** [comment]
Hi @aFrontendDev, thanks for your patience. I'm happy to report that the issue you raised has been resolved in the upcoming v0.11.0 release. I've added a test to specifically cover this scenario, and I've also verified the fix in the demo. Everything is looking good.

**Comment by theisel** [comment]
Closing this issue as it has been resolved. The resolution was verified by the test added in this commit: https://github.com/theisel/astro-portabletext/commit/761d67b216229e37d6181001cd028192b396eac9

**Comment by aFrontendDev** [comment]
Amazing, thanks @theisel

**Comment by theisel** [comment]
Hi @aFrontendDev, just wanted to let you know that v0.11.0 has  released, and it includes a fix for the issue you reported.  Please let me know if you encounter any further problems.
