### ISSUE TITLE
Suggestion: also export spanToPlainText from @portabletext/toolkit

### ISSUE THREAD

**Issue by fvieira** [theisel/astro-portabletext#178]
In order to build a custom component that needs to know the size of the text it will render, I had to install `@portabletext/toolkit` just to get access to `spanToPlainText`. It would be nice if this library exported it too, just like it exports `toPlainText`.

**Comment by theisel** [comment]
Hi @fvieira, thanks for the suggestion! I'll add `spanToPlainText` to the exports and plan to release a new version later today.

**Comment by fvieira** [comment]
@theisel Wow, that was fast! Thanks a lot, I've updated my code and removed the extra dependency.
